/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmngmnt;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class module1 extends javax.swing.JFrame {

    /**
     * Creates new form module1
     */
    public module1() {
        initComponents();
        
       
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        CNIC = new javax.swing.JTextField();
        ill = new javax.swing.JComboBox<>();
        PI = new javax.swing.JTextField();
        CD = new javax.swing.JTextField();
        doctor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        datelab = new javax.swing.JLabel();
        da = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("         PATIENT FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 35, 599, 73));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter Patient Information");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 115, -1, 52));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Patient Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 241, 140, 34));

        pn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnActionPerformed(evt);
            }
        });
        getContentPane().add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 241, 482, 34));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Father's Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 293, 140, 39));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("MObile Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 345, -1, 37));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Patient Illness");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 405, 140, 47));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Choose Doctor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 487, 140, 30));

        fn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 293, 482, 39));

        CNIC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(CNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 345, 482, 42));

        ill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Orthopedic", "Medicine", "Fever", "Aids", "Cancer", "Covid-19" }));
        getContentPane().add(ill, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 414, 90, 32));

        PI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(PI, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 405, 482, 47));

        CD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(CD, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 487, 482, 30));

        doctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dr.ovi", "Dr.Fahim", "Dr.patwary", "Dr.Saidur", "Dr.Rayna" }));
        getContentPane().add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 487, -1, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 563, 97, 44));

        datelab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datelab.setText("Date");
        getContentPane().add(datelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 130, 61, 27));

        da.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 130, 196, 27));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Cancel");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 563, 77, 34));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmngmnt/6.jpg"))); // NOI18N
        jLabel9.setText("j");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 410, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pname = pn.getText();
        String fname = fn.getText();
        String Cnic = CNIC.getText();
        String date = da.getText();
        
        
        PI.setText(ill.getSelectedItem().toString());
        CD.setText(doctor.getSelectedItem().toString());
        
        JOptionPane.showMessageDialog(rootPane,"Patient Name   "+pname+"\nFather Name"+fname+"\nPhone number"+Cnic+"\nDate"+date+"\n\n Data hasbeen Submited");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        
          MenuPage obj = new MenuPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(module1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(module1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(module1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(module1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new module1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CD;
    private javax.swing.JTextField CNIC;
    private javax.swing.JTextField PI;
    private javax.swing.JTextField da;
    private javax.swing.JLabel datelab;
    private javax.swing.JComboBox<String> doctor;
    private javax.swing.JTextField fn;
    private javax.swing.JComboBox<String> ill;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pn;
    // End of variables declaration//GEN-END:variables
}
